name: "Build iloader"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: write
    env:
      HAVE_SIGNING_SECRETS: ${{ secrets.DEV_ID_P12_BASE64 != '' && secrets.DEV_ID_P12_PASSWORD != '' && secrets.DEV_IDENTITY_NAME != '' }}
      HAVE_NOTARIZE_SECRETS: ${{ secrets.NOTARIZE_APPLE_ID != '' && secrets.NOTARIZE_APP_SPECIFIC_PASS != '' && secrets.NOTARIZE_TEAM_ID != '' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Cache Rust, Bun and frontend dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
            node_modules
            ~/.bun/install/cache
          key: windows-iloader-${{ hashFiles('**/Cargo.lock', 'package-lock.json', 'bun.lock') }}
          restore-keys: |
            Windows-iloader-

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Add MSVC to PATH
        shell: pwsh
        run: |
          Write-Host "MSVC environment provided by windows-latest"

      - name: Install frontend dependencies
        run: npm install

      - name: Build
        run: npm run tauri build
